from hocort.pipelines.bowtie2 import Bowtie2
from hocort.pipelines.bowtie2_hisat2 import Bowtie2HISAT2
from hocort.pipelines.bowtie2_bowtie2 import Bowtie2Bowtie2
from hocort.pipelines.bwa_mem2 import BWA_MEM2
from hocort.pipelines.hisat2 import HISAT2
from hocort.pipelines.minimap2 import Minimap2
from hocort.pipelines.kraken2 import Kraken2
from hocort.pipelines.kraken2_bowtie2 import Kraken2Bowtie2
from hocort.pipelines.kraken2_minimap2 import Kraken2Minimap2
from hocort.pipelines.bbmap import BBMap
